#! /bin/bash
# https://hub.docker.com/_/postgres
#
# for client cmd connection
# sudo apt-get -y install postgresql
# psql -h localhost -U postgres -d postgres


# remove when done
# docker run --rm --name atasq-dev-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:16.1

# detached
docker run -d --restart always --name atasq-dev-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:16.1
