#! /bin/bash
# https://hub.docker.com/_/postgres
#
# for client cmd connection
# sudo apt-get -y install postgresql
# psql -h localhost -U postgres -d postgres


# remove when done
# docker run --rm --name atasq-dev-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:16.1

# detached
docker run -d --restart always --name atasq-dev-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:16.1
docker run -d --restart always --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:8.11.3

docker exec elasticsearch bash -c 'yes | (echo -en "y\nelastic\nelastic\n" ; cat) | bin/elasticsearch-reset-password -i -u elastic --url https://localhost:9200'
