# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
# https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

name: Tag Release Workflow

on:
  push:
    # tags:
    # - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "20.10.x"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Build Package
      run: |
        echo Version(GITHUB_REF): ${GITHUB_REF##*/}
        ./scripts/build ${GITHUB_REF##*/}
